workflows:
  flutter-connect-ios:
    name: Flutter iOS Connect
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - push
      - tag
      - pull_request
    scripts:
      - name: Verify directory & run Flutter commands
        script: |
          echo "Current directory:"
          pwd
          ls -la
          echo "=== Entering grocery_shop_app ==="
          cd grocery_shop_app
          pwd
          ls -la
          flutter pub get
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app