// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4tQ103TTpxiaNQio74G0c3fhhkoJ5VE',
    appId: '1:286709854618:web:478f8dcf10bc4d15cb0a23',
    messagingSenderId: '286709854618',
    projectId: 'grocery-96b92',
    authDomain: 'grocery-96b92.firebaseapp.com',
    storageBucket: 'grocery-96b92.firebasestorage.app',
    measurementId: 'G-ZZE9ECJREX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6qFdo4C9zp1oV2bUzQwck2hLLXrEkpMA',
    appId: '1:286709854618:android:a67c5083fea5157acb0a23',
    messagingSenderId: '286709854618',
    projectId: 'grocery-96b92',
    storageBucket: 'grocery-96b92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoM312744GXk9hJqaF5v6OJ59Q0wX7ZqM',
    appId: '1:286709854618:ios:a4095221f45df10ccb0a23',
    messagingSenderId: '286709854618',
    projectId: 'grocery-96b92',
    storageBucket: 'grocery-96b92.firebasestorage.app',
    iosBundleId: 'com.example.groceryShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoM312744GXk9hJqaF5v6OJ59Q0wX7ZqM',
    appId: '1:286709854618:ios:a4095221f45df10ccb0a23',
    messagingSenderId: '286709854618',
    projectId: 'grocery-96b92',
    storageBucket: 'grocery-96b92.firebasestorage.app',
    iosBundleId: 'com.example.groceryShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA4tQ103TTpxiaNQio74G0c3fhhkoJ5VE',
    appId: '1:286709854618:web:f3e7f082bad131e2cb0a23',
    messagingSenderId: '286709854618',
    projectId: 'grocery-96b92',
    authDomain: 'grocery-96b92.firebaseapp.com',
    storageBucket: 'grocery-96b92.firebasestorage.app',
    measurementId: 'G-GJ41WMHQNQ',
  );
}
