// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQW_W15WJH9TPfDOYq3kGsMOnSpMxTUgc',
    appId: '1:440422523094:web:2487d12fb92c3ab9df2977',
    messagingSenderId: '440422523094',
    projectId: 'grocery-485ea',
    authDomain: 'grocery-485ea.firebaseapp.com',
    storageBucket: 'grocery-485ea.firebasestorage.app',
    measurementId: 'G-66LF0VMMVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc16ofMikeePQCOf09sGK_twIwxUsNFCg',
    appId: '1:440422523094:android:23aa00c9d69879a6df2977',
    messagingSenderId: '440422523094',
    projectId: 'grocery-485ea',
    storageBucket: 'grocery-485ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu-7DKtrQ_v3zYT1SquVlk-ETgjHqCsco',
    appId: '1:440422523094:ios:b0df2212f4c3f5a5df2977',
    messagingSenderId: '440422523094',
    projectId: 'grocery-485ea',
    storageBucket: 'grocery-485ea.firebasestorage.app',
    iosBundleId: 'com.example.groceryAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu-7DKtrQ_v3zYT1SquVlk-ETgjHqCsco',
    appId: '1:440422523094:ios:b0df2212f4c3f5a5df2977',
    messagingSenderId: '440422523094',
    projectId: 'grocery-485ea',
    storageBucket: 'grocery-485ea.firebasestorage.app',
    iosBundleId: 'com.example.groceryAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQW_W15WJH9TPfDOYq3kGsMOnSpMxTUgc',
    appId: '1:440422523094:web:de96f333498dc5b7df2977',
    messagingSenderId: '440422523094',
    projectId: 'grocery-485ea',
    authDomain: 'grocery-485ea.firebaseapp.com',
    storageBucket: 'grocery-485ea.firebasestorage.app',
    measurementId: 'G-6C11MJ8M3Y',
  );
}
